import numpy as np
import matplotlib.pyplot as plt
import os

# Parameters as defined in calculate_sorting.py
Ls = [8, 10, 12, 14, 16, 18, 20]
gi = 1.5
gf = 0.5
angle = 0.0
t_start = 0.0
dt = 0.01
Ndt = 100
ts = [5,10,15, 20,25, 30,35, 40,45, 50, 60, 70, 80, 90]
candidates=100
# Calculate the physical time step t


# Reconstruct the file path used in calculate_sorting.py
output_dir = "wavefunctions_data"
two_sortings = [True]

# Formatting the plots
for t_idx in ts:
    t = t_start + t_idx * dt
    plt.figure(figsize=(8, 5))
    #plt.yscale('log')
    plt.ylim([1e-11,1.1])
    plt.xlabel(r'$n_c/L$')
    #plt.xlim([0,2.1])
    plt.ylabel('fidelity')
    plt.title(f'fidelity vs Parameters | $g_i$={gi}, $g_f$={gf}, angle={angle}, t={t:.2f}')
    plt.grid(True, which="both", linestyle="--", alpha=0.6)
    plt.tight_layout()

    for sort in two_sortings:
        for L in Ls: 
            base_name_inf = f"inf_L{L}gi{gi:.2f}gf{gf:.2f}ti{t_start}dt{dt}t{t_idx}Nt{Ndt}C{sort}.npy"
            filename_inf = os.path.join(output_dir, base_name_inf)
            if not os.path.exists(filename_inf):
                raise FileNotFoundError(f"Cannot find the data file: {filename_inf}. Ensure calculate_sorting.py has been run.")

            # Load the data generated by calculate_sorting.py
            inf_data = 1-np.load(filename_inf)

            # The x-axis represents the number of parameters added during the sweep
            num_parameters = np.arange(1, len(inf_data) + 1)/L

        # Plotting the infidelity curve

            plt.plot(num_parameters, inf_data.real, marker='o', markersize=10, linestyle='-',label=str(sort)+",L="+str(L))

    
    # Save the figure to the same directory as the data
    plot_filename = os.path.join(output_dir, f"plot_f_gi{gi:.2f}gf{gf:.2f}t{t_idx}.png")
    plt.legend(fontsize=15)
    plt.savefig(plot_filename, dpi=300, bbox_inches='tight')
    print(f"Plot saved successfully to: {plot_filename}")

    # Display the plot
    plt.show()
