import numpy as np
import matplotlib.pyplot as plt
import os

# Parameters as defined in calculate_sorting.py
L = 10
gi = 1.5
gf = 0.5
angle = 0.0
t_start = 0.0
dt = 0.01
Ndt = 100
t_idx = 60
candidates=100
# Calculate the physical time step t
t = t_start + t_idx * dt

# Reconstruct the file path used in calculate_sorting.py
output_dir = "wavefunctions_data"
base_name_inf = f"inf_L{L}gi{gi:.2f}gf{gf:.2f}ti{t_start}dt{dt}t{t_idx}candidates{candidates}Nt{Ndt}.npy"
filename_inf = os.path.join(output_dir, base_name_inf)

if not os.path.exists(filename_inf):
    raise FileNotFoundError(f"Cannot find the data file: {filename_inf}. Ensure calculate_sorting.py has been run.")

# Load the data generated by calculate_sorting.py
inf_data = np.load(filename_inf)

# The x-axis represents the number of parameters added during the sweep
num_parameters = np.arange(1, len(inf_data) + 1)

# Plotting the infidelity curve
plt.figure(figsize=(8, 5))
plt.plot(num_parameters, inf_data.real, marker='o', markersize=2, linestyle='-', color='#1f77b4')

# Formatting the plot
plt.yscale('log')
plt.xlabel('Number of Parameters')
plt.ylabel('Infidelity')
plt.title(f'Infidelity vs Parameters | L={L}, $g_i$={gi}, $g_f$={gf}, angle={angle}, t={t:.2f}')
plt.grid(True, which="both", linestyle="--", alpha=0.6)
plt.tight_layout()

# Save the figure to the same directory as the data
plot_filename = os.path.join(output_dir, f"plot_inf_L{L}gi{gi:.2f}gf{gf:.2f}t{t_idx}.png")
plt.savefig(plot_filename, dpi=300, bbox_inches='tight')
print(f"Plot saved successfully to: {plot_filename}")

# Display the plot
plt.show()
